### ISSUE TITLE
Variable name

### ISSUE THREAD

**Issue by nicolab28** [snapwich/richsnapp.com#2]
Could you add an underscore at the end of the variable names, to be able to differentiate the variables like let99 from let999, like this let99_ and let999_
Because when you're renaming in batches, don't get lost
thank you

**Comment by snapwich** [comment]
sorry for the slow response. this seems like a good idea though so i've added it in https://github.com/snapwich/richsnapp.com/commit/b435d3261938cf6a8a1dd97387fc9ff6856b82de
