### ISSUE TITLE
put code unmangler into its own repo

### ISSUE THREAD

**Issue by 3052** [snapwich/richsnapp.com#3]
https://www.richsnapp.com/tools/code-unmangler

this is cool, but I think it should be in its own repo, so people can post issues on it specifically. also it would be cool if you could run the tool from the command line

**Comment by snapwich** [comment]
i agree with you. unfortunately the way i structured my site with these little widgets as basically nuxt page components they are not something that would be easily removed without a refactor and i just don't have the will to do that anytime soon. sorry!
